### ISSUE TITLE
Error in ginv(info) : could not find function "ginv"

### ISSUE THREAD

**Issue by dchiu911** [dlinzer/poLCA#18]
Need to add `MASS::` to `ginv()` [here](https://github.com/dlinzer/poLCA/blob/master/R/poLCA.R#L104)
Otherwise you get errors of
```
Error in ginv(info) : could not find function "ginv"
```
if you run `poLCA::poLCA()` (without attaching via `library(poLCA)`)

**Comment by JeffreyBLewis** [comment]
Fixed in Version 1.6.
